${javarel}/modules/toolbox/bn-filterbuilder/bn-filterbuilder.inc
${javarel}/modules/toolbox/bn-commons-constants/bn-commons-constants.inc
${javarel}/modules/toolbox/bn-commons-i18n/bn-commons-i18n.inc
${javarel}/modules/toolbox/bn-commons/bn-commons.inc
${javarel}/modules/toolbox/bn-testutils/bn-testutils.inc
${javarel}/modules/business/bn-sensorserver/bn-sensorserver.inc
${javarel}/modules/business/bn-sensoroverview/bn-sensoroverview.inc
${javarel}/tools/apachecxf/apachecxf.inc